'use strict';window.DOMHandler=class{constructor(a,b){this._iRuntime=a;this._componentId=b;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(a,b,c,d){this._iRuntime.PostToRuntimeComponent(this._componentId,a,b,c,d)}PostToRuntimeAsync(a,b,c,d){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,a,b,c,d)}_PostToRuntimeMaybeSync(a,b,c){this._iRuntime.UsesWorker()?this.PostToRuntime(a,b,c):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:a,dispatchOpts:c||null,data:b,responseId:null})}AddRuntimeMessageHandler(a,b){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,a,b)}AddRuntimeMessageHandlers(a){for(const [b,c]of a)this.AddRuntimeMessageHandler(b,c)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(a,b){this._callback=a;this._interval=b;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(a){this._canRunImmediate=!!a}Call(){if(-1===this._timerId){var a=Date.now(),b=a-this._lastCallTime,c=this._interval;b>=c&&this._canRunImmediate?(this._lastCallTime=a,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(c-b,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};


'use strict';window.DOMElementHandler=class extends self.DOMHandler{constructor(a,b){super(a,b);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandler("create",a=>this._OnCreate(a));this.AddRuntimeMessageHandler("destroy",a=>this._OnDestroy(a));this.AddRuntimeMessageHandler("set-visible",a=>this._OnSetVisible(a));this.AddRuntimeMessageHandler("update-position",a=>this._OnUpdatePosition(a));this.AddRuntimeMessageHandler("update-state",a=>this._OnUpdateState(a));this.AddRuntimeMessageHandler("focus",
a=>this._OnSetFocus(a));this.AddRuntimeMessageHandler("set-css-style",a=>this._OnSetCssStyle(a));this.AddDOMElementMessageHandler("get-element",a=>a)}SetAutoAttach(a){this._autoAttach=!!a}AddDOMElementMessageHandler(a,b){this.AddRuntimeMessageHandler(a,a=>{const c=this._elementMap.get(a.elementId);return b(c,a)})}_OnCreate(a){const b=a.elementId,c=this.CreateElement(b,a);this._elementMap.set(b,c);a.isVisible||(c.style.display="none");this._autoAttach&&document.body.appendChild(c)}CreateElement(a,
b){throw Error("required override");}DestroyElement(a){}_OnDestroy(a){a=a.elementId;const b=this._elementMap.get(a);this.DestroyElement(b);this._autoAttach&&b.parentElement.removeChild(b);this._elementMap.delete(a)}PostToRuntimeElement(a,b,c){c||(c={});c.elementId=b;this.PostToRuntime(a,c)}_PostToRuntimeElementMaybeSync(a,b,c){c||(c={});c.elementId=b;this._PostToRuntimeMaybeSync(a,c)}_OnSetVisible(a){this._autoAttach&&(this._elementMap.get(a.elementId).style.display=a.isVisible?"":"none")}_OnUpdatePosition(a){if(this._autoAttach){var b=
this._elementMap.get(a.elementId);b.style.left=a.left+"px";b.style.top=a.top+"px";b.style.width=a.width+"px";b.style.height=a.height+"px";a=a.fontSize;null!==a&&(b.style.fontSize=a+"em")}}_OnUpdateState(a){const b=this._elementMap.get(a.elementId);this.UpdateState(b,a)}UpdateState(a,b){throw Error("required override");}_OnSetFocus(a){const b=this._elementMap.get(a.elementId);a.focus?b.focus():b.blur()}_OnSetCssStyle(a){this._elementMap.get(a.elementId).style[a.prop]=a.val}GetElementById(a){return this._elementMap.get(a)}};


'use strict';{var IsWebViewExportType=function(f){return w.has(f)},BlobToArrayBuffer=function(f){return new Promise((a,b)=>{const c=new FileReader;c.onload=b=>a(b.target.result);c.onerror=a=>b(a);c.readAsArrayBuffer(f)})},BlobToString=async function(f){f=await BlobToArrayBuffer(f);return(new TextDecoder("utf-8")).decode(f)},AddScript=function(f){if(f.isStringSrc){const a=document.createElement("script");a.async=!1;a.textContent=f.str;document.head.appendChild(a)}else return new Promise((a,b)=>{const c=
document.createElement("script");c.onload=a;c.onerror=b;c.async=!1;c.src=f;document.head.appendChild(c)})};const t=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let l=new Audio;const u={"audio/webm; codecs=opus":!!l.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!l.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!l.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!l.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!l.canPlayType("audio/mp4"),
"audio/mpeg":!!l.canPlayType("audio/mpeg")};l=null;const p=[];let m=0;window.RealFile=window.File;const n=[],q=new Map,r=new Map;let x=0;const v=[];self.runOnStartup=function(f){if("function"!==typeof f)throw Error("runOnStartup called without a function");v.push(f)};const w=new Set(["cordova","playable-ad","instant-games"]);window.RuntimeInterface=class f{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptBlobURLs=
{};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;IsWebViewExportType(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this._useWorker=!1);this._transferablesBroken=!1;this._localFileStrings=
this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",a=>this._OnCordovaFetchLocalFile(a));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",a=>this._OnCreateJobWorker(a));
"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}IsiOSCordova(){return t&&
"cordova"===this._exportType}IsiOSWebView(){return t&&IsWebViewExportType(this._exportType)||navigator.standalone}async _Init(a){if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let c=0,d=a.engineScripts.length;c<d;++c){var b=a.engineScripts[c].toLowerCase();this._localFileStrings.hasOwnProperty(b)?a.engineScripts[c]={isStringSrc:!0,str:this._localFileStrings[b]}:this._localFileBlobs.hasOwnProperty(b)&&
(a.engineScripts[c]=URL.createObjectURL(this._localFileBlobs[b]))}}a.baseUrl?this._baseUrl=a.baseUrl:(b=location.origin,this._baseUrl=("null"===b?"file:///":b)+location.pathname,b=this._baseUrl.lastIndexOf("/"),-1!==b&&(this._baseUrl=this._baseUrl.substr(0,b+1)));if(a.workerScripts)for(const [b,d]of Object.entries(a.workerScripts))this._workerScriptBlobURLs[b]=URL.createObjectURL(d);b=new MessageChannel;this._messageChannelPort=b.port1;this._messageChannelPort.onmessage=a=>this._OnMessageFromRuntime(a.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(a=>this._OnMessageFromDebugger(a));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();this.MaybeForceBodySize();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this._TestTransferablesWork();this._useWorker?await this._InitWorker(a,b.port2):await this._InitDOM(a,b.port2)}_GetWorkerURL(a){return this._workerScriptBlobURLs.hasOwnProperty(a)?
this._workerScriptBlobURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptBlobURLs.hasOwnProperty("workermain.js")?this._workerScriptBlobURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?URL.createObjectURL(this._localFileBlobs[a.toLowerCase()]):a}async CreateWorker(a,b,c){if(a.startsWith("blob:"))return new Worker(a,c);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+
a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),c);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),c)}return new Worker(a,c)}MaybeForceBodySize(){if(this.IsiOSWebView()){const a=document.documentElement.style,b=document.body.style,c=window.innerWidth<window.innerHeight,d=c?window.screen.width:window.screen.height;b.height=a.height=(c?window.screen.height:
window.screen.width)+"px";b.width=a.width=d+"px"}}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),
supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,b){var c=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(c,this._baseUrl,{name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display=
"none";c=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:c,workerDependencyScripts:a.workerDependencyScripts||[],engineScripts:a.engineScripts,projectScripts:window.cr_allProjectScripts,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,c,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=n.map(a=>
new a(this));this._FindRuntimeDOMHandler();self.c3_callFunction=(a,b)=>this._runtimeDomHandler._InvokeFunctionFromJS(a,b);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,b){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=n.map(a=>new a(this));this._FindRuntimeDOMHandler();const c=a.engineScripts.map(a=>
"string"===typeof a?(new URL(a,this._baseUrl)).toString():a);Array.isArray(a.workerDependencyScripts)&&c.unshift(...a.workerDependencyScripts);await Promise.all(c.map(a=>AddScript(a)));if(a.projectScripts&&0<a.projectScripts.length){const b=self.C3_ProjectScriptsStatus;try{if(await Promise.all(a.projectScripts.map(a=>AddScript(a[1]))),Object.values(b).some(a=>!a)){self.setTimeout(()=>this._ReportProjectScriptError(b),100);return}}catch(e){console.error("[Preview] Error loading project scripts: ",
e);self.setTimeout(()=>this._ReportProjectScriptError(b),100);return}}"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),{isInWorker:!1,messagePort:b,canvas:this._canvas,runOnStartupFunctions:v}),this._localRuntime=
self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectScriptError(a){a=`Failed to load project script '${Object.entries(a).filter(a=>!a[1]).map(a=>a[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+a);alert(a)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,
b,c,d,e){this._messageChannelPort.postMessage({type:"event",component:a,handler:b,dispatchOpts:d||null,data:c,responseId:null},this._transferablesBroken?void 0:e)}PostToRuntimeComponentAsync(a,b,c,d,e){const g=x++,h=new Promise((a,b)=>{r.set(g,{resolve:a,reject:b})});this._messageChannelPort.postMessage({type:"event",component:a,handler:b,dispatchOpts:d||null,data:c,responseId:g},this._transferablesBroken?void 0:e);return h}["_OnMessageFromRuntime"](a){const b=a.type;if("event"===b)return this._OnEventFromRuntime(a);
if("result"===b)this._OnResultFromRuntime(a);else if("runtime-ready"===b)this._OnRuntimeReady();else if("alert"===b)alert(a.message);else throw Error(`unknown message '${b}'`);}_OnEventFromRuntime(a){const b=a.component,c=a.handler,d=a.data,e=a.responseId;if(a=q.get(b))if(a=a.get(c)){var g=null;try{g=a(d)}catch(h){console.error(`Exception in '${b}' handler '${c}':`,h);null!==e&&this._PostResultToRuntime(e,!1,""+h);return}if(null===e)return g;g&&g.then?g.then(a=>this._PostResultToRuntime(e,!0,a)).catch(a=>
{console.error(`Rejection from '${b}' handler '${c}':`,a);this._PostResultToRuntime(e,!1,""+a)}):this._PostResultToRuntime(e,!0,g)}else console.warn(`[DOM] No handler '${c}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}_PostResultToRuntime(a,b,c){let d;c&&c.transferables&&(d=c.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:b,result:c},d)}_OnResultFromRuntime(a){const b=a.responseId,c=a.isOk;a=a.result;const d=r.get(b);
c?d.resolve(a):d.reject(a);r.delete(b)}AddRuntimeComponentMessageHandler(a,b,c){let d=q.get(a);d||(d=new Map,q.set(a,d));if(d.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);d.set(b,c)}static AddDOMHandlerClass(a){if(n.includes(a))throw Error("DOM handler already added");n.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger",
"message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");
this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!u[a]}async _WasmDecodeWebMOpus(a){a=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _OnCordovaFetchLocalFile(a){const b=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(b);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(b);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=
window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,b){a=a[b];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const b=this._GetPermissionAPI();return new Promise((c,d)=>b.checkPermission(this._MapPermissionID(b,a),a=>c(!!a.hasPermission),d))}_RequestPermission(a){const b=this._GetPermissionAPI();return new Promise((c,d)=>b.requestPermission(this._MapPermissionID(b,
a),a=>c(!!a.hasPermission),d))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const b of a)if(!await this._HasPermission(b)&&!1===await this._RequestPermission(b))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const b=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((a,d)=>{window.resolveLocalFileSystemURL(b,
b=>{b.file(a,d)},d)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await BlobToString(a)}_CordovaMaybeStartNextArrayBufferRead(){if(p.length&&!(8<=m)){m++;var a=p.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((b,c)=>{p.push({filename:a,successCallback:a=>{m--;this._CordovaMaybeStartNextArrayBufferRead();b(a)},errorCallback:a=>{m--;this._CordovaMaybeStartNextArrayBufferRead();
c(a)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,b,c){try{const c=await this.CordovaFetchLocalFile(a),e=await BlobToArrayBuffer(c);b(e)}catch(d){c(d)}}async _ConvertDataUrisToBlobs(){const a=[];for(const [b,c]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(b,c));await Promise.all(a)}async _ConvertDataUriToBlobs(a,b){if("object"===typeof b)this._localFileBlobs[a]=new Blob([b.str],{type:b.type}),this._localFileStrings[a]=
b.str;else{let c=await this._FetchDataUri(b);c||(c=this._DataURIToBinaryBlobSync(b));this._localFileBlobs[a]=c}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",b),null}}_DataURIToBinaryBlobSync(a){a=this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var b=
a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var c=a.substring(5,b);a=a.substring(b+1);b=c.split(";");c=b[0]||"";const d=b[2];a="base64"===b[1]||"base64"===d?atob(a):decodeURIComponent(a);return{mime_type:c,data:a}}_BinaryStringToBlob(a,b){var c=a.length;let d=c>>2,e=new Uint8Array(c),g=new Uint32Array(e.buffer,0,d),h,k;for(k=h=0;h<d;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(c&=3;c--;)e[k]=a.charCodeAt(k),++k;return new Blob([e],
{type:b})}_TestTransferablesWork(){let a=null;const b=new Promise(b=>a=b),c=new ArrayBuffer(1),d=new MessageChannel;d.port2.onmessage=b=>{b.data&&b.data.arrayBuffer||(this._transferablesBroken=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));a()};d.port1.postMessage({arrayBuffer:c},[c]);return b}}};


'use strict';{var KeyboardIsVisible=function(){const a=document.activeElement;if(!a)return!1;const b=a.tagName.toLowerCase(),c=new Set("email number password search tel text url".split(" "));return"textarea"===b?!0:"input"===b?c.has(a.type.toLowerCase()||"text"):IsInContentEditable(a)},ParentHasFocus=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}},BlockWheelZoom=function(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()},PreventDefaultOnCanvasOrDoc=function(a){const b=
a.target.tagName.toLowerCase();m.has(b)&&a.preventDefault()},IsInContentEditable=function(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;a=a.parentNode}while(a);return!1},BlobToSvgImage=async function(a,b,c){if(!/firefox/i.test(navigator.userAgent))return await BlobToImage(a);var d=await BlobToString(a);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const b=e.getAttribute("width"),d=e.getAttribute("height");
if(!b.includes("%")&&!d.includes("%"))return await BlobToImage(a)}e.setAttribute("width",b+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);a=new Blob([d],{type:"image/svg+xml"});return await BlobToImage(a)},BlobToString=function(a){return new Promise((b,c)=>{let d=new FileReader;d.onload=a=>b(a.target.result);d.onerror=a=>c(a);d.readAsText(a)})},BlobToImage=async function(a){a=URL.createObjectURL(a);try{return await FetchImage(a)}finally{URL.revokeObjectURL(a)}},FetchImage=
function(a){return new Promise((b,c)=>{const d=new Image;d.onload=()=>b(d);d.onerror=a=>c(a);d.src=a})},AddStyleSheet=function(a){return new Promise((b,c)=>{const d=document.createElement("link");d.onload=()=>b(d);d.onerror=a=>c(a);d.rel="stylesheet";d.href=a;document.head.appendChild(d)})},IsCompatibilityMouseEvent=function(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents};
const h=self.RuntimeInterface,n=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),f={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},l={dispatchUserScriptEvent:!0},p={dispatchRuntimeEvent:!0},m=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(a){a=await BlobToImage(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const b=a.getBoundingClientRect();
document.body.removeChild(a);return[b.width,b.height]}};self.C3_RasterSvgImageBlob=async function(a,b,c,d,e){a=await BlobToSvgImage(a,b,c);const g=document.createElement("canvas");g.width=d;g.height=e;g.getContext("2d").drawImage(a,0,0,b,c);return g};let k=!1;document.addEventListener("pause",()=>k=!0);document.addEventListener("resume",()=>k=!1);h.AddDOMHandlerClass(class extends self.DOMHandler{constructor(a){super(a,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation=
"any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=this._debugHighlightElem=null;a.AddRuntimeComponentMessageHandler("canvas","update-size",a=>this._OnUpdateCanvasSize(a));a.AddRuntimeComponentMessageHandler("runtime","invoke-download",a=>this._OnInvokeDownload(a));a.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",a=>this._OnRasterSvgImage(a));a.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",
a=>this._OnGetSvgImageSize(a));a.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",a=>this._OnSetTargetOrientation(a));a.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());a.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",a=>this._OnPostToDebugger(a));a.AddRuntimeComponentMessageHandler("runtime","go-to-script",a=>this._OnPostToDebugger(a));a.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());
a.AddRuntimeComponentMessageHandler("runtime","debug-highlight",a=>this._OnDebugHighlight(a));a.AddRuntimeComponentMessageHandler("runtime","enable-device-orientation",()=>this._AttachDeviceOrientationEvent());a.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());a.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",a=>this._OnAddStylesheet(a));a.AddRuntimeComponentMessageHandler("runtime","alert",a=>this._OnAlert(a));const b=new Set(["input",
"textarea","datalist"]);window.addEventListener("contextmenu",a=>{const c=a.target,d=c.tagName.toLowerCase();b.has(d)||IsInContentEditable(c)||a.preventDefault()});const c=a.GetCanvas();window.addEventListener("selectstart",PreventDefaultOnCanvasOrDoc);window.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);c.addEventListener("selectstart",PreventDefaultOnCanvasOrDoc);c.addEventListener("gesturehold",PreventDefaultOnCanvasOrDoc);window.addEventListener("touchstart",PreventDefaultOnCanvasOrDoc,
{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc,{passive:!1}),c.addEventListener("pointerdown",PreventDefaultOnCanvasOrDoc)):c.addEventListener("touchstart",PreventDefaultOnCanvasOrDoc);this._mousePointerLastButtons=0;window.addEventListener("mousedown",a=>{1===a.button&&a.preventDefault()});window.addEventListener("mousewheel",BlockWheelZoom,{passive:!1});window.addEventListener("wheel",BlockWheelZoom,{passive:!1});window.addEventListener("resize",
()=>this._OnWindowResize());a.IsiOSWebView()&&window.addEventListener("focusout",()=>{KeyboardIsVisible()||(document.scrollingElement.scrollTop=0)});this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));
return{isSuspended:!(!document.hidden&&!k)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:ParentHasFocus()});this._mousePointerLastButtons=0});window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());
window.addEventListener("fullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("webkitfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("mozfullscreenerror",a=>this._OnFullscreenError(a));window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,f));window.addEventListener("wheel",a=>this._OnMouseWheelEvent("wheel",
a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)}),this._iRuntime.UsesWorker()&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",a=>this._OnPointerRawUpdate(a))):window.addEventListener("pointermove",
a=>this._OnPointerEvent("pointermove",a)),window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a)),window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",a))):(window.addEventListener("mousedown",a=>{this._HandlePointerDownFocus(a);this._OnMouseEventAsPointer("pointerdown",a)}),window.addEventListener("mousemove",a=>this._OnMouseEventAsPointer("pointermove",a)),window.addEventListener("mouseup",a=>this._OnMouseEventAsPointer("pointerup",a)),window.addEventListener("touchstart",
a=>{this._HandlePointerDownFocus(a);this._OnTouchEvent("pointerdown",a)}),window.addEventListener("touchmove",a=>this._OnTouchEvent("pointermove",a)),window.addEventListener("touchend",a=>this._OnTouchEvent("pointerup",a)),window.addEventListener("touchcancel",a=>this._OnTouchEvent("pointercancel",a)));const a=()=>this._PlayPendingMedia();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);
window.addEventListener("gamepadconnected",a,!0)}_PostRuntimeEvent(a,b){this.PostToRuntime(a,b||null,p)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_OnWindowResize(){const a=this._GetWindowInnerWidth(),b=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:a,innerHeight:b,devicePixelRatio:window.devicePixelRatio});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),
this._OnSimulatedResize(a,b,0))}_ScheduleSimulatedResize(a,b,c){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>this._OnSimulatedResize(a,b,c),48)}_OnSimulatedResize(a,b,c){const d=this._GetWindowInnerWidth(),e=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;d!=a||e!=b?this._PostRuntimeEvent("window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio}):10>c&&this._ScheduleSimulatedResize(d,
e,c+1)}_OnSetTargetOrientation(a){this._targetOrientation=a.targetOrientation}_TrySetTargetOrientation(){const a=this._targetOrientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let b=!1;screen.lockOrientation?b=screen.lockOrientation(a):screen.webkitLockOrientation?b=screen.webkitLockOrientation(a):screen.mozLockOrientation?b=screen.mozLockOrientation(a):screen.msLockOrientation&&(b=screen.msLockOrientation(a));
b||console.warn("[Construct 3] Failed to lock orientation")}catch(b){console.warn("[Construct 3] Failed to lock orientation: ",b)}}_OnFullscreenChange(){const a=h.IsDocumentFullscreen();a&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:a,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(a){console.warn("[Construct 3] Fullscreen request failed: ",a);this.PostToRuntime("fullscreenerror",
{isFullscreen:h.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(a){a?this._iRuntime._CancelAnimationFrame():this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:a})}_OnKeyEvent(a,b){"Backspace"===b.key&&PreventDefaultOnCanvasOrDoc(b);const c=n.get(b.code)||b.code;this._PostToRuntimeMaybeSync(a,{code:c,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,
shiftKey:b.shiftKey,timeStamp:b.timeStamp},f)}_OnMouseWheelEvent(a,b){this.PostToRuntime(a,{clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,deltaX:b.deltaX,deltaY:b.deltaY,deltaZ:b.deltaZ,deltaMode:b.deltaMode,timeStamp:b.timeStamp},f)}_OnMouseEvent(a,b,c){IsCompatibilityMouseEvent(b)||this._PostToRuntimeMaybeSync(a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,timeStamp:b.timeStamp},c)}_OnMouseEventAsPointer(a,b){if(!IsCompatibilityMouseEvent(b)){var c=
this._mousePointerLastButtons;"pointerdown"===a&&0!==c?a="pointermove":"pointerup"===a&&0!==b.buttons&&(a="pointermove");this._PostToRuntimeMaybeSync(a,{pointerId:1,pointerType:"mouse",button:b.button,buttons:b.buttons,lastButtons:c,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:b.timeStamp},f);this._mousePointerLastButtons=b.buttons;this._OnMouseEvent(b.type,b,l)}}_OnPointerEvent(a,b){this._pointerRawUpdateRateLimiter&&
"pointermove"!==a&&this._pointerRawUpdateRateLimiter.Reset();var c=0;"mouse"===b.pointerType&&(c=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:c,clientX:b.clientX,clientY:b.clientY,pageX:b.pageX,pageY:b.pageY,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},f);"mouse"===
b.pointerType&&(c="mousemove","pointerdown"===a?c="mousedown":"pointerup"===a&&(c="pointerup"),this._OnMouseEvent(c,b,l),this._mousePointerLastButtons=b.buttons)}_OnPointerRawUpdate(a){this._lastPointerRawUpdateEvent=a;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(a,b){for(let c=0,d=b.changedTouches.length;c<d;++c){const d=b.changedTouches[c];this._PostToRuntimeMaybeSync(a,
{pointerId:d.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:2*(d.radiusX||d.webkitRadiusX||0),height:2*(d.radiusY||d.webkitRadiusY||0),pressure:d.force||d.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:d.rotationAngle||0,timeStamp:b.timeStamp},f)}}_HandlePointerDownFocus(a){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(a.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&
document.activeElement.blur()}_IsElementCanvasOrDocument(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",a=>this._OnDeviceOrientation(a)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",a=>this._OnDeviceMotion(a)))}_OnDeviceOrientation(a){this.PostToRuntime("deviceorientation",
{alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},f)}_OnDeviceMotion(a){let b=null;var c=a.acceleration;c&&(b={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var d=a.accelerationIncludingGravity;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const e=a.rotationRate;e&&(d={alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0});this.PostToRuntime("devicemotion",{acceleration:b,accelerationIncludingGravity:c,rotationRate:d,interval:a.interval,timeStamp:a.timeStamp},f)}_OnUpdateCanvasSize(a){const b=
this.GetRuntimeInterface(),c=b.GetCanvas();c.style.width=a.styleWidth+"px";c.style.height=a.styleHeight+"px";c.style.marginLeft=a.marginLeft+"px";c.style.marginTop=a.marginTop+"px";b.MaybeForceBodySize();this._isFirstSizeUpdate&&(c.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(a){const b=a.url;a=a.filename;const c=document.createElement("a"),d=document.body;c.textContent=a;c.href=b;c.download=a;d.appendChild(c);c.click();d.removeChild(c)}async _OnRasterSvgImage(a){var b=a.imageBitmapOpts;
a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);b=b?await createImageBitmap(a,b):await createImageBitmap(a);return{imageBitmap:b,transferables:[b]}}async _OnGetSvgImageSize(a){return await self.C3_GetSvgImageSize(a.blob)}async _OnAddStylesheet(a){await AddStyleSheet(a.url)}_PlayPendingMedia(){var a=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const b of a)(a=b.play())&&a.catch(a=>{this._mediaRemovedPendingPlay.has(b)||
this._mediaPendingPlay.add(b)})}TryPlayMedia(a){if("function"!==typeof a.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(a);let b;try{b=a.play()}catch(c){this._mediaPendingPlay.add(a);return}b&&b.catch(b=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}RemovePendingPlay(a){this._mediaPendingPlay.delete(a);this._mediaRemovedPendingPlay.add(a)}SetSilent(a){this._isSilent=!!a}_OnDebugHighlight(a){if(a.show){this._debugHighlightElem||(this._debugHighlightElem=
document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var b=this._debugHighlightElem;b.style.display="";b.style.left=a.left-1+"px";b.style.top=a.top-1+"px";b.style.width=a.width+2+"px";b.style.height=a.height+2+"px";b.textContent=a.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display="none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(a){window.c3_postToMessagePort&&
(a.from="runtime",window.c3_postToMessagePort(a))}_InvokeFunctionFromJS(a,b){return this.PostToRuntimeAsync("js-invoke-function",{name:a,params:b})}_OnAlert(a){alert(a.message)}})};


'use strict';{const d=document.currentScript.src;self.JobSchedulerDOM=class{constructor(a){this._runtimeInterface=a;this._baseUrl=d?d.substr(0,d.lastIndexOf("/")+1):a.GetBaseURL();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var a=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(a,this._baseUrl,{name:"DispatchWorker"});a=new MessageChannel;this._inputPort=a.port1;this._dispatchWorker.postMessage({type:"_init","in-port":a.port2},[a.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const a=this._jobWorkers.length;var b=this._runtimeInterface._GetWorkerURL("jobworker.js");b=await this._runtimeInterface.CreateWorker(b,this._baseUrl,{name:"JobWorker"+a});const c=new MessageChannel,e=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":e.port2},[c.port2,e.port2]);this._jobWorkers.push(b);return e.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}}};


'use strict';if(window.C3_IsSupported){const a="undefined"!==typeof OffscreenCanvas;window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:false&&a,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"})};
'use strict';var StopKeyPropagation=function(b){13!==b.which&&27!==b.which&&b.stopPropagation()},StopPropagation=function(b){b.stopPropagation()};
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"text-input");this.AddDOMElementMessageHandler("scroll-to-bottom",b=>this._OnScrollToBottom(b))}CreateElement(b,c){let a;const d=c.type;"textarea"===d?(a=document.createElement("textarea"),a.style.resize="none"):(a=document.createElement("input"),a.type=d);a.style.position="absolute";a.autocomplete="off";a.addEventListener("touchstart",StopPropagation);a.addEventListener("touchmove",StopPropagation);
a.addEventListener("touchend",StopPropagation);a.addEventListener("mousedown",StopPropagation);a.addEventListener("mouseup",StopPropagation);a.addEventListener("keydown",StopKeyPropagation);a.addEventListener("keyup",StopKeyPropagation);a.addEventListener("click",a=>{a.stopPropagation();this._PostToRuntimeElementMaybeSync("click",b)});a.addEventListener("dblclick",a=>{a.stopPropagation();this._PostToRuntimeElementMaybeSync("dblclick",b)});a.addEventListener("input",()=>this.PostToRuntimeElement("change",
b,{text:a.value}));a.id=c.id;this.UpdateState(a,c);return a}UpdateState(b,c){b.value=c.text;b.placeholder=c.placeholder;b.title=c.title;b.disabled=!c.isEnabled;b.readOnly=c.isReadOnly;b.spellcheck=c.spellCheck}_OnScrollToBottom(b){b.scrollTop=b.scrollHeight}});
'use strict';var StopPropagation=function(b){b.stopPropagation()};
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(b){super(b,"button")}CreateElement(b,d){const c=document.createElement("input");var a=c;d.isCheckbox?(c.type="checkbox",a=document.createElement("label"),a.appendChild(c),a.appendChild(document.createTextNode("")),a.style.fontFamily="sans-serif",a.style.userSelect="none",a.style.webkitUserSelect="none",a.style.display="inline-block",a.style.color="black"):c.type="button";a.style.position="absolute";a.addEventListener("touchstart",
StopPropagation);a.addEventListener("touchmove",StopPropagation);a.addEventListener("touchend",StopPropagation);a.addEventListener("mousedown",StopPropagation);a.addEventListener("mouseup",StopPropagation);a.addEventListener("keydown",StopPropagation);a.addEventListener("keyup",StopPropagation);c.addEventListener("click",()=>this._PostToRuntimeElementMaybeSync("click",b,{isChecked:c.checked}));c.id=d.id;this.UpdateState(a,d);return a}_GetInputElem(b){return"input"===b.tagName.toLowerCase()?b:b.firstChild}UpdateState(b,
d){const c=this._GetInputElem(b);c.checked=d.isChecked;c.disabled=!d.isEnabled;b.title=d.title;b===c?c.value=d.text:b.lastChild.textContent=d.text}});
